/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/huoxd/Desktop/leyuan/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-972c371a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-972c371a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7a5f75e8",
    path: "/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a5f75e8").then(next)
    },
  },
  {
    name: "v-7abd2386",
    path: "/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7abd2386").then(next)
    },
  },
  {
    name: "v-50e0c54e",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50e0c54e").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-a128c536",
    path: "/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a128c536").then(next)
    },
  },
  {
    path: "/faq/index.html",
    redirect: "/faq/"
  },
  {
    name: "v-8470ecf0",
    path: "/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8470ecf0").then(next)
    },
  },
  {
    name: "v-55aad20c",
    path: "/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55aad20c").then(next)
    },
  },
  {
    name: "v-4b815880",
    path: "/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b815880").then(next)
    },
  },
  {
    name: "v-0de267f0",
    path: "/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0de267f0").then(next)
    },
  },
  {
    name: "v-9a9da330",
    path: "/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9a9da330").then(next)
    },
  },
  {
    name: "v-159e90b0",
    path: "/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-159e90b0").then(next)
    },
  },
  {
    name: "v-e0faa4f0",
    path: "/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e0faa4f0").then(next)
    },
  },
  {
    name: "v-2d814a52",
    path: "/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d814a52").then(next)
    },
  },
  {
    name: "v-fd0d2db0",
    path: "/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fd0d2db0").then(next)
    },
  },
  {
    name: "v-0b7847b0",
    path: "/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0b7847b0").then(next)
    },
  },
  {
    name: "v-16a5fb7e",
    path: "/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16a5fb7e").then(next)
    },
  },
  {
    name: "v-304c3948",
    path: "/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-304c3948").then(next)
    },
  },
  {
    name: "v-5980dee8",
    path: "/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5980dee8").then(next)
    },
  },
  {
    name: "v-2bba9736",
    path: "/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2bba9736").then(next)
    },
  },
  {
    name: "v-e9cce2f0",
    path: "/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e9cce2f0").then(next)
    },
  },
  {
    name: "v-1f42697a",
    path: "/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f42697a").then(next)
    },
  },
  {
    path: "/plugin/index.html",
    redirect: "/plugin/"
  },
  {
    name: "v-97d52498",
    path: "/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-97d52498").then(next)
    },
  },
  {
    name: "v-bbfb8930",
    path: "/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bbfb8930").then(next)
    },
  },
  {
    name: "v-0bba21d8",
    path: "/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bba21d8").then(next)
    },
  },
  {
    name: "v-616c9446",
    path: "/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-616c9446").then(next)
    },
  },
  {
    name: "v-549b5d88",
    path: "/plugin/official/plugin-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-549b5d88").then(next)
    },
  },
  {
    name: "v-d65b38f0",
    path: "/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d65b38f0").then(next)
    },
  },
  {
    name: "v-84aaf070",
    path: "/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84aaf070").then(next)
    },
  },
  {
    name: "v-b5fc617c",
    path: "/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b5fc617c").then(next)
    },
  },
  {
    name: "v-3aaf3722",
    path: "/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3aaf3722").then(next)
    },
  },
  {
    name: "v-1a31bc88",
    path: "/plugin/official/plugin-pagination.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a31bc88").then(next)
    },
  },
  {
    name: "v-61ec7124",
    path: "/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61ec7124").then(next)
    },
  },
  {
    name: "v-39b1b898",
    path: "/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39b1b898").then(next)
    },
  },
  {
    name: "v-b3cc0a70",
    path: "/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3cc0a70").then(next)
    },
  },
  {
    name: "v-4f62d4f0",
    path: "/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f62d4f0").then(next)
    },
  },
  {
    name: "v-8afc5602",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8afc5602").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-46957088",
    path: "/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46957088").then(next)
    },
  },
  {
    name: "v-1d68f264",
    path: "/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d68f264").then(next)
    },
  },
  {
    name: "v-75812588",
    path: "/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75812588").then(next)
    },
  },
  {
    name: "v-0ff1bac8",
    path: "/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ff1bac8").then(next)
    },
  },
  {
    name: "v-5e47b863",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e47b863").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-67f9b170",
    path: "/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67f9b170").then(next)
    },
  },
  {
    name: "v-fce3af40",
    path: "/zh/api/cli.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fce3af40").then(next)
    },
  },
  {
    name: "v-3968f208",
    path: "/zh/api/node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3968f208").then(next)
    },
  },
  {
    name: "v-068341fa",
    path: "/zh/faq/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-068341fa").then(next)
    },
  },
  {
    path: "/zh/faq/index.html",
    redirect: "/zh/faq/"
  },
  {
    name: "v-01fd5bc3",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01fd5bc3").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    name: "v-06182c68",
    path: "/zh/guide/basic-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06182c68").then(next)
    },
  },
  {
    name: "v-39097a68",
    path: "/zh/guide/assets.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39097a68").then(next)
    },
  },
  {
    name: "v-461b4ce8",
    path: "/zh/guide/deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-461b4ce8").then(next)
    },
  },
  {
    name: "v-bdcb8a14",
    path: "/zh/guide/directory-structure.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bdcb8a14").then(next)
    },
  },
  {
    name: "v-cce594f0",
    path: "/zh/guide/frontmatter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cce594f0").then(next)
    },
  },
  {
    name: "v-a1b2d528",
    path: "/zh/guide/getting-started.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a1b2d528").then(next)
    },
  },
  {
    name: "v-1da38aa4",
    path: "/zh/guide/global-computed.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1da38aa4").then(next)
    },
  },
  {
    name: "v-56c123c8",
    path: "/zh/guide/i18n.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56c123c8").then(next)
    },
  },
  {
    name: "v-5341a624",
    path: "/zh/guide/markdown-slot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5341a624").then(next)
    },
  },
  {
    name: "v-13b4a828",
    path: "/zh/guide/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13b4a828").then(next)
    },
  },
  {
    name: "v-ccf90af0",
    path: "/zh/guide/permalinks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ccf90af0").then(next)
    },
  },
  {
    name: "v-2ef8ace2",
    path: "/zh/guide/using-vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ef8ace2").then(next)
    },
  },
  {
    name: "v-11c99197",
    path: "/zh/inside/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11c99197").then(next)
    },
  },
  {
    path: "/zh/inside/index.html",
    redirect: "/zh/inside/"
  },
  {
    name: "v-d82e9bf8",
    path: "/zh/miscellaneous/design-concepts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d82e9bf8").then(next)
    },
  },
  {
    name: "v-6217c4a8",
    path: "/zh/inside/env.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6217c4a8").then(next)
    },
  },
  {
    name: "v-15450808",
    path: "/zh/miscellaneous/glossary.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15450808").then(next)
    },
  },
  {
    name: "v-fe3a6184",
    path: "/zh/miscellaneous/migration-guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe3a6184").then(next)
    },
  },
  {
    name: "v-4c54b269",
    path: "/zh/plugin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4c54b269").then(next)
    },
  },
  {
    path: "/zh/plugin/index.html",
    redirect: "/zh/plugin/"
  },
  {
    name: "v-10e392e8",
    path: "/zh/plugin/context-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10e392e8").then(next)
    },
  },
  {
    name: "v-de0ba658",
    path: "/zh/plugin/life-cycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-de0ba658").then(next)
    },
  },
  {
    name: "v-58ed4a28",
    path: "/zh/plugin/official/plugin-active-header-links.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58ed4a28").then(next)
    },
  },
  {
    name: "v-0db79b08",
    path: "/zh/plugin/official/plugin-back-to-top.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0db79b08").then(next)
    },
  },
  {
    name: "v-3e655664",
    path: "/zh/plugin/official/plugin-blog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e655664").then(next)
    },
  },
  {
    name: "v-1b5ac9ae",
    path: "/zh/plugin/official/plugin-google-analytics.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b5ac9ae").then(next)
    },
  },
  {
    name: "v-3bb1fd0a",
    path: "/zh/plugin/official/plugin-last-updated.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3bb1fd0a").then(next)
    },
  },
  {
    name: "v-69e6ee70",
    path: "/zh/plugin/official/plugin-medium-zoom.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69e6ee70").then(next)
    },
  },
  {
    name: "v-136bbb70",
    path: "/zh/plugin/official/plugin-nprogress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-136bbb70").then(next)
    },
  },
  {
    name: "v-5ea9f69e",
    path: "/zh/plugin/official/plugin-pagination.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ea9f69e").then(next)
    },
  },
  {
    name: "v-1ede3630",
    path: "/zh/plugin/official/plugin-pwa.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ede3630").then(next)
    },
  },
  {
    name: "v-035d7628",
    path: "/zh/plugin/official/plugin-register-components.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-035d7628").then(next)
    },
  },
  {
    name: "v-a0d1a6fc",
    path: "/zh/plugin/official/plugin-search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0d1a6fc").then(next)
    },
  },
  {
    name: "v-7599abc4",
    path: "/zh/plugin/writing-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7599abc4").then(next)
    },
  },
  {
    name: "v-70681d2e",
    path: "/zh/plugin/using-a-plugin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70681d2e").then(next)
    },
  },
  {
    name: "v-d87f663a",
    path: "/zh/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d87f663a").then(next)
    },
  },
  {
    path: "/zh/theme/index.html",
    redirect: "/zh/theme/"
  },
  {
    name: "v-493c40ee",
    path: "/zh/theme/inheritance.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-493c40ee").then(next)
    },
  },
  {
    name: "v-4879ddb0",
    path: "/zh/theme/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4879ddb0").then(next)
    },
  },
  {
    name: "v-fe97b2cc",
    path: "/zh/theme/using-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe97b2cc").then(next)
    },
  },
  {
    name: "v-22de18ac",
    path: "/zh/theme/writing-a-theme.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22de18ac").then(next)
    },
  },
  {
    name: "v-03fff13a",
    path: "/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03fff13a").then(next)
    },
  },
  {
    path: "/config/index.html",
    redirect: "/config/"
  },
  {
    name: "v-e02bad70",
    path: "/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e02bad70").then(next)
    },
  },
  {
    name: "v-02a3ad44",
    path: "/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02a3ad44").then(next)
    },
  },
  {
    name: "v-76d17b8b",
    path: "/zh/config/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76d17b8b").then(next)
    },
  },
  {
    path: "/zh/config/index.html",
    redirect: "/zh/config/"
  },
  {
    name: "v-56c65f8c",
    path: "/zh/plugin/option-api.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56c65f8c").then(next)
    },
  },
  {
    name: "v-9f8eb230",
    path: "/zh/theme/default-theme-config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9f8eb230").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]