/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/huoxd/Desktop/FUCK/VUEPRESS/vuepress_init/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-73887561",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73887561").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7e455ed1",
    path: "/zh/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e455ed1").then(next)
    },
  },
  {
    path: "/zh/index.html",
    redirect: "/zh/"
  },
  {
    name: "v-539740f6",
    path: "/zh/inside/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-539740f6").then(next)
    },
  },
  {
    path: "/zh/inside/index.html",
    redirect: "/zh/inside/"
  },
  {
    name: "v-37867b7a",
    path: "/zh/inside/env.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37867b7a").then(next)
    },
  },
  {
    name: "v-44e6070c",
    path: "/zh/customer/leyuan/leyuan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44e6070c").then(next)
    },
  },
  {
    name: "v-d99e71c4",
    path: "/zh/inside/leyuan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d99e71c4").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]