/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，可以在 Markdown 中使用 Vue 组件，又可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 会为每个页面预渲染生成静态的 HTML，同时，每个页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-7e455ed1",
      "path": "/zh/",
      "headers": [
        {
          "level": 3,
          "title": "像数 1, 2, 3 一样容易",
          "slug": "像数-1-2-3-一样容易"
        }
      ],
      "lastUpdated": "2019-5-9 19:32:24"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "actionText": "进入 →",
        "actionLink": "/zh/inside/",
        "footer": "LINEWIT"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-73887561",
      "path": "/",
      "lastUpdated": "2019-5-9 19:32:24"
    },
    {
      "title": "BS",
      "frontmatter": {},
      "regularPath": "/zh/customer/leyuan/leyuan.html",
      "relativePath": "zh/customer/leyuan/leyuan.md",
      "key": "v-44e6070c",
      "path": "/zh/customer/leyuan/leyuan.html",
      "headers": [
        {
          "level": 2,
          "title": "初始配置",
          "slug": "初始配置"
        },
        {
          "level": 2,
          "title": "设备巡检",
          "slug": "设备巡检"
        },
        {
          "level": 2,
          "title": "日结算",
          "slug": "日结算"
        }
      ]
    },
    {
      "title": "说明",
      "frontmatter": {},
      "regularPath": "/zh/inside/",
      "relativePath": "zh/inside/README.md",
      "key": "v-539740f6",
      "path": "/zh/inside/",
      "lastUpdated": "2019-5-9 20:46:35"
    },
    {
      "title": "环境搭建",
      "frontmatter": {},
      "regularPath": "/zh/inside/env.html",
      "relativePath": "zh/inside/env.md",
      "key": "v-37867b7a",
      "path": "/zh/inside/env.html",
      "headers": [
        {
          "level": 2,
          "title": "需要文件",
          "slug": "需要文件"
        }
      ],
      "lastUpdated": "2019-5-9 20:46:35"
    },
    {
      "title": "APP",
      "frontmatter": {},
      "regularPath": "/zh/inside/leyuan.html",
      "relativePath": "zh/inside/leyuan.md",
      "key": "v-d99e71c4",
      "path": "/zh/inside/leyuan.html",
      "headers": [
        {
          "level": 2,
          "title": "服务端返回图片的路径",
          "slug": "服务端返回图片的路径"
        },
        {
          "level": 2,
          "title": "由于扩展配置问题而无法提供您的请求页面",
          "slug": "由于扩展配置问题而无法提供您的请求页面"
        }
      ]
    }
  ],
  "themeConfig": {
    "editLinks": true,
    "docsDir": "packages/docs/docs",
    "locales": {
      "/": {
        "label": "简体中文",
        "selectText": "选择语言",
        "lastUpdated": "上次更新",
        "nav": [
          {
            "text": "内部",
            "link": "/zh/inside/"
          },
          {
            "text": "对外",
            "items": [
              {
                "text": "徐州乐园",
                "link": "/zh/customer/leyuan/leyuan.html"
              },
              {
                "text": "MES"
              }
            ]
          }
        ],
        "sidebar": {
          "/zh/inside/": [
            {
              "title": "MES",
              "collapsable": false,
              "children": [
                "",
                "env"
              ]
            },
            {
              "title": "徐州乐园",
              "collapsable": false,
              "children": [
                "leyuan"
              ]
            }
          ],
          "/zh/customer/leyuan/": [
            {
              "title": "操作说明",
              "collapsable": false,
              "children": [
                "leyuan"
              ]
            }
          ]
        }
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "蓝今项目跟踪",
      "description": "问题记录",
      "path": "/"
    }
  }
}